version: "3.9"

services:
  dezpray-server:
    image: dezpray-server
    container_name: dezpray-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
